---
# Handler for the webtier: handlers are called by other plays.
# See http://docs.ansible.com/playbooks_intro.html for more information about handlers.

- name: restart iptables
  service: name=iptables state=restarted
  sudo: yes

- name: restart webservice
  service: name=httpd state=restarted
  sudo: yes
