---
- name: Check if Drupal is already set up.
  stat: "path={{ drupal_core_path }}/index.php"
  register: drupal_site
  notify: checking if drupal is already set

#- name: Copy drush makefile.
#  copy: src=drush.make dest=/var/www/html/
#  sudo: yes
#  when: drupal_site.stat.exists == false

#- name: Generate Drupal site with drush makefile.
#  command: drush make -y /var/www/html/drush.make chdir=/var/www/html/
#  sudo: yes
#  when: drupal_site.stat.exists == false

#- name: Install configured modules with drush.
#  command: >
#    drush en -y {{ drupal_enable_modules | join(" ") }}
#    chdir={{ drupal_core_path }}
#  when: drupal_site.stat.exists == false

# Download Drupal using Git.
- name: Check out Drupal Core to the default location.
  git: >
    repo={{ drupal_repo_url }}
    version={{ drupal_core_version }}
    update={{ drupal_keep_updated }}
    dest={{ drupal_core_path }}
    force=yes
  sudo: yes
  when: drupal_site.stat.exists == false

- name: Install Drupal (standard profile) with drush.
  command: >
    drush si {{ drupal_install_profile | default('standard') }} -y
    --locale="{{ drupal_locale }}"
    --site-name="{{ drupal_site_name }}"
    --site-mail="{{ drupal_site_mail }}"
    --account-name={{ drupal_admin_name }}"
    --account-pass={{ drupal_admin_pass }}"
    --account-mail={{ drupal_admin_mail }}
    --db-url="{{ drupal_db_url }}"
    chdir={{ drupal_core_path }}
  sudo: yes
  notify: restart webserver
  when: drupal_site.stat.exists == false