---
# These tasks install http and the php modules.

- name: Install http and php etc
  yum: name={{ item }} state=present
  with_items:
   - httpd
   - php
   - php-mysql
   - php-gd
   - php-dom
   - php-mbstring
   - git
   - libsemanage-python
   - libselinux-python
  sudo: yes
  tags: httpd

- name: insert iptables rule for httpd
  lineinfile: dest=/etc/sysconfig/iptables create=yes state=present regexp="{{ httpd_port }}" insertafter="^:OUTPUT "
              line="-A INPUT -p tcp  --dport {{ httpd_port }} -j  ACCEPT"
  sudo: yes
  notify: restart iptables
  tags: httpd

- name: http service state
  service: name=httpd state=started enabled=yes
  sudo: yes
  tags: httpd

- name: Configure SELinux to allow httpd to connect to remote database
  seboolean: name=httpd_can_network_connect_db state=true persistent=yes 
  sudo: yes
  when: sestatus.rc != 0
  tags: httpd
